markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: pingking
author: "PingKing"
email: running_ping@163.com
name: "PingKing's blog"
url: http://pingking.tk
domain: pingking.tk
all_categories: [
#
#["android", "Android","/posts/android.html"], 
#["program", "软件编程","/posts/program.html"],
#["algorithm", "Web建站","/posts/algorithm.html"], 
#["linux", "Linux相关","/posts/linux.html"],
#["read", "读书笔记","/posts/read.html"], 
#["other", "杂记","/posts/other.html"],
#["about", "关于","/about.html"]
["programming","Programming","/posts/programming.html"],
["linux", "Linux","/posts/linux.html"],
["algorithm", "Algorithm","/posts/algorithm.html"],
["japanese", "Foreign language","/posts/japanese.html"],
["read", "Reading & Life","/posts/read.html"], 
["other", "Other","/posts/other.html"],
["tips", "Tips","/posts/tips.html"],
["about", "About","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles
#highlighter:rouge

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
